language: shell

matrix:
  include:
    - os: linux
      env: OS=Linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
    - os: windows
      env: OS=Windows
  fast_finish: true

install:
  - bin/install-pester.sh

before_script:
  - bin/fetch-configlet
  - bin/configlet lint .

script:
  - bin/run-tests.sh
